/** @type {import('tailwindcss').Config} */
export default {
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
        "dark",
        "light",
        "acid",
        "aqua",
        "autumn",
        "black",
        "bumblebee",
        "business",
        "coffee",
        "corporate",
        "cupcake",
        "cyberpunk",
        "cmyk",
        "dim",
        "dracula",
        "emerald",
        "fantasy",
        "forest",
        "garden",
        "halloween",
        "lemonade",
        "light",
        "lofi",
        "luxury",
        "night",
        "nord",
        "pastel",
        "retro",
        "sunset",
        "synthwave",
        "valentine",
        "winter",
        "wireframe",
    ],
  },
};
